objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>GW_Volunteers__Number_of_Volunteers__c</fullName>
        <inlineHelpText>The total number of volunteers whose Hours Status = Completed or Confirmed.</inlineHelpText>
        <label>Number of Volunteers</label>
        <summarizedField>GW_Volunteers__Volunteer_Job__c.GW_Volunteers__Number_of_Volunteers__c</summarizedField>
        <summaryForeignKey>GW_Volunteers__Volunteer_Job__c.GW_Volunteers__Campaign__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Head_Count__c</fullName>
        <description>How many people are signed up or attended this campaign</description>
        <label>Head Count</label>
        <summarizedField>CampaignMember.Party_of__c</summarizedField>
        <summaryForeignKey>CampaignMember.CampaignId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Participant_Days__c</fullName>
        <description>The number of Participant Days in this Adventure (this is the days in the adventure multiplied by the total number of people that experienced the adventure - participants, friends and family, caregivers, invitees, volunteers and staff).</description>
        <inlineHelpText>The number of Participant Days in this Adventure (this is the days in the adventure multiplied by the total number of people that experienced the adventure - participants, friends and family, caregivers, invitees, volunteers and staff).</inlineHelpText>
        <label>Participant Days</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Related_Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related campaign for this record Adventure-Volunteer campaign relationship.</description>
        <label>Related Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Related Campaign</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Adventure</fullName>
        <active>true</active>
        <description>Outdoor Recreation Activities</description>
        <label>Adventure</label>
    </recordTypes>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

classes/add_all_attending.cls
global class add_all_attending {
    @InvocableMethod
    global static void TotParticipantDays (List<Campaign> adventures){
        List<Campaign> updAdv = new List<Campaign>();
        //retrieve the volunteer campaign corresponding to the adventure campaings
        //first make a list with all the volunteer campaign id's to retrieve all the vol campaigns
        list<id> volId = new list<id>();
        for (campaign c : adventures){
            volId.add(c.Related_Campaign__c);
            updAdv.add(c);
        }
        //using the list of id's retrieve the volunteer campaigns
        map<id, campaign> volunteers = new map<id, campaign>([SELECT id, GW_Volunteers__Number_of_Volunteers__c
                                                             FROM Campaign WHERE id IN :volId]);
        //calculate the Total Participant Days for each campaign and 
        for (campaign c : updAdv){
            integer days = c.EndDate.daysBetween(c.StartDate) + 1;
            system.debug('days = ' + days);
            integer totAttending = integer.valueOf(c.Head_Count__c) + 
                integer.valueOf(volunteers.get(c.Related_Campaign__c).GW_Volunteers__Number_of_Volunteers__c);
            system.debug('totAttending = ' + totAttending);
            c.Participant_Days__c = days * totAttending;
            system.debug('participant days = ' + c.Participant_Days__c);
        }
        update updAdv;
    }

}